version: '3.7'

services:
  test-gilded-rose:
    container_name: test-gilded-rose
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    restart: unless-stopped
    stdin_open: true
    tty: true
