version: '3.7'

services:
  test-temp-tracker:
    container_name: test-temp-tracker
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    restart: unless-stopped
    stdin_open: true
    tty: true
